### Receiver manual test to receiver
POST http://localhost:5262/webhooks/receive/generic
Content-Type: application/json
X-API-Key: your-api-key
X-Webhook-Signature: sha256=abc123...

{"message": "Hello webhook!"}

### For register suscription
POST http://localhost:5262/api/webhooks/subscriptions
Content-Type: application/json

{
    "url": "http://localhost:5262/webhooks/receive/generic",
    "events": ["order.created", "order.updated"],
    "description": "Order processing webhook",
    "maxRetries": 1,
    "retryDelayMinutes": 1
}

### for single subcription
GET http://localhost:5262/api/webhooks/subscriptions/5af0a84f-2d7f-49d3-9476-93cf0e80ee4b/trigger
Content-Type: application/json
### for test all events subsriptions
POST http://localhost:5262/api/webhooks/events
Content-Type: application/json

{
    "eventType": "order.created",
    "source": "OrderService",
    "data": {
        "orderId": "12345",
        "customerId": "67890",
        "amount": 99.99,
        "currency": "USD"
    }
}
