@baseUrl = http://localhost:5136
@sampleId = 3fa85f64-5717-4562-b3fc-2c963f66afa6

###
# Función reutilizable para validar respuestas exitosas
### ==========================================
### BOOK APIS
### ==========================================

### Obtener lista de libros
GET {{baseUrl}}/api/books?Filter=Clean&SkipCount=0&MaxResultCount=10&Sorting=title

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Crear libro
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "title": "El resplandor",
  "author": "Stephen King",
  "publishDate": "2026-07-13T12:00:00Z"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Buscar por autor
GET {{baseUrl}}/api/books/by-author?author=Stephen%20King

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### ==========================================
### CATEGORY APIS
### ==========================================

### Listar categorías
GET {{baseUrl}}/api/categories?SkipCount=0&MaxResultCount=10&Sorting=name

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### ==========================================
### STUDENT APIS
### ==========================================

### Listar estudiantes
GET {{baseUrl}}/api/student?SkipCount=0&MaxResultCount=10

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Crear estudiante
POST {{baseUrl}}/api/student
Content-Type: application/json

{
  "title": "Nombre del Estudiante",
  "author": "Carrera",
  "publishDate": "2026-07-13T12:00:00Z"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}



### ==========================================
### TODO APIS
### ==========================================

### Listar Todos
GET {{baseUrl}}/api/todos?SkipCount=0&MaxResultCount=10

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Crear Todo
POST {{baseUrl}}/api/todos
Content-Type: application/json

{
  "title": "Terminar la documentación de la API",
  "isCompleted": false
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### ==========================================
### MANIFEST
### ==========================================

GET {{baseUrl}}/api/manifest/v2

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}