using QuestPDF.Companion;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;

namespace QuestPdfDocument;

public abstract class DocumentTemplateBase
{
    protected Universidad Universidad { get; set; } = MockData.Universidad;
    protected DocumentoOpciones DocumentOptions { get; set; } = MockData.OpcionesDocumento;

    public bool EnableWatermark { get; set; } = false;
    public string? WatermarkText { get; set; } = "INTERNAL DOCUMENT";

    public string? FooterMessage { get; set; } = "Document generated by the University Tutoring Management System - AKDEMIC TUTORÍA";

    public IDocument Generate()
    {
        return Document.Create(BuildDocument);
    }

    public void GeneratePdf(string outputPath)
    {
        Generate().GeneratePdf(outputPath);
    }

    public void ShowCompanion()
    {
        Document.Create(BuildDocument).ShowInCompanion();
    }

    protected virtual void BuildDocument(IDocumentContainer container)
    {
        container.Page(page =>
        {
            ConfigurePage(page);
            ApplyPageWatermark(page);
            RenderHeader(page);
            page.Content()
                .PaddingHorizontal(30)
                .Column(Content);
            RenderFooter(page);
        });
    }

    protected virtual void ConfigurePage(PageDescriptor page)
    {
        page.ConfigureBasePage();
    }

    protected virtual void ApplyPageWatermark(PageDescriptor page)
    {
        if (!EnableWatermark || string.IsNullOrWhiteSpace(WatermarkText)) return;
        page.ApplyWatermark(options =>
        {
            options.Enabled = true;
            options.Text = WatermarkText;
        });
    }

    protected virtual void RenderHeader(PageDescriptor page)
    {
        page.BuildHeader(Universidad);
    }

    protected virtual void RenderFooter(PageDescriptor page)
    {
        page.BuildFooter(Universidad, footerMessage: FooterMessage);
    }

    protected abstract void Content(ColumnDescriptor column);
}

public class LetterTemplate : DocumentTemplateBase
{
    public string FullLetterNumber => $"{DocumentOptions.SequenceStart}{DocumentOptions.NumeroCarta}";

    public string Date { get; set; } = MockData.OpcionesDocumento.FechaGenerada;
    public string RecipientName { get; set; } = string.Empty;
    public string? RecipientDetail1 { get; set; }
    public string? RecipientDetail2 { get; set; }
    public string? RecipientDetail3 { get; set; }
    public string Subject { get; set; } = string.Empty;
    public string InitialGreeting { get; set; } = "Of my special consideration;";
    public List<string> BodyParagraphs { get; set; } = new();
    public List<ILetterSection> Sections { get; set; } = new();
    public string? ClosingParagraph { get; set; }
    public string Closing { get; set; } = "Sincerely,";
    public SignatureData? SenderSignature { get; set; }

    protected override void Content(ColumnDescriptor column)
    {
        column.Spacing(5);

        column.Item().Text(Date).AlignEnd().FontSize(10);
        column.Item().PaddingBottom(10)
            .Text($"LETTER N° {FullLetterNumber}")
            .AlignStart().Underline().Bold();

        if (!string.IsNullOrWhiteSpace(RecipientDetail3) || !string.IsNullOrWhiteSpace(RecipientDetail2) || !string.IsNullOrWhiteSpace(RecipientDetail1))
            column.Item().Text("Mr(s):").AlignStart();
        column.Item().Text(RecipientName.ToUpper()).AlignStart().Bold();
        if (!string.IsNullOrWhiteSpace(RecipientDetail1)) column.Item().Text(RecipientDetail1).AlignStart();
        if (!string.IsNullOrWhiteSpace(RecipientDetail2)) column.Item().Text(RecipientDetail2).AlignStart();
        if (!string.IsNullOrWhiteSpace(RecipientDetail3)) column.Item().Text(RecipientDetail3).AlignStart();
        column.Item().PaddingBottom(10).Text("HEREBY.-").AlignStart().Underline();

        column.Item().Text(t =>
        {
            t.Span("SUBJECT: ").Bold();
            t.Span(Subject);
        });

        column.Item().PaddingVertical(5).Text(InitialGreeting);

        foreach (var paragraph in BodyParagraphs)
        {
            column.Item().Text(t =>
            {
                t.Justify();
                t.Span(paragraph);
            });
        }

        foreach (var section in Sections)
        {
            section.Render(column);
        }

        if (!string.IsNullOrWhiteSpace(ClosingParagraph))
        {
            column.Item().PaddingTop(15).Text(t =>
            {
                t.Justify();
                t.Span(ClosingParagraph);
            });
        }

        column.Item().PaddingVertical(10).Text(Closing).AlignCenter();

        if (SenderSignature != null)
        {
            column.Item().PaddingTop(20).Column(sigCol =>
            {
                sigCol.Item().AlignCenter().Text("_______________________________").FontSize(10);
                sigCol.Item().AlignCenter().Text(SenderSignature.Name).Bold().FontSize(10);
                if (!string.IsNullOrWhiteSpace(SenderSignature.Position))
                    sigCol.Item().AlignCenter().Text(SenderSignature.Position).FontSize(9);
                if (!string.IsNullOrWhiteSpace(SenderSignature.Institution))
                    sigCol.Item().AlignCenter().Text(SenderSignature.Institution).FontSize(9);
            });
        }
    }
}

public interface ILetterSection
{
    string SectionTitle { get; }
    void Render(ColumnDescriptor column);
}

public class ListSection : ILetterSection
{
    public string SectionTitle { get; set; } = string.Empty;
    public List<string> Items { get; set; } = new();
    public bool Numbered { get; set; } = true;
    public float ItemFontSize { get; set; } = 10;
    public bool JustifyItems { get; set; } = true;

    public void Render(ColumnDescriptor column)
    {
        if (!string.IsNullOrWhiteSpace(SectionTitle))
            column.Item().PaddingBottom(5).Text(SectionTitle).Bold().FontSize(10).Underline();

        column.Item().Column(listCol =>
        {
            foreach (var (item, index) in Items.Select((it, i) => (it, i + 1)))
            {
                listCol.Item().PaddingLeft(5).PaddingVertical(2).Text(tx =>
                {
                    if (JustifyItems) tx.Justify();
                    if (Numbered)
                    {
                        tx.Span($"{index}. ").Bold().FontSize(ItemFontSize);
                    }
                    else
                    {
                        tx.Span("•  ").Bold().FontSize(ItemFontSize);
                    }
                    tx.Span(item).FontSize(ItemFontSize);
                });
            }
        });
    }
}

public class KeyValueTableSection : ILetterSection
{
    public string SectionTitle { get; set; } = string.Empty;
    public List<(string Label, string Value)> Rows { get; set; } = new();
    public int ColumnsPerRow { get; set; } = 2;

    public void Render(ColumnDescriptor column)
    {
        if (!string.IsNullOrWhiteSpace(SectionTitle))
            column.Item().PaddingTop(10).PaddingBottom(5)
                .Text(SectionTitle).Bold().FontSize(10).Underline();

        column.Item().PaddingTop(5).PaddingBottom(10).Table(table =>
        {
            table.ColumnsDefinition(definition =>
            {
                for (var i = 0; i < ColumnsPerRow; i++)
                {
                    definition.ConstantColumn(3.5f, Unit.Centimetre);
                    definition.RelativeColumn(1);
                }
            });

            for (var i = 0; i < Rows.Count; i += ColumnsPerRow)
            {
                for (var col = 0; col < ColumnsPerRow; col++)
                {
                    var idx = i + col;
                    if (idx < Rows.Count)
                    {
                        var (label, value) = Rows[idx];
                        table.Cell().Border(0.5f).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Background(QuestPDF.Helpers.Colors.Grey.Lighten4)
                            .Padding(4).Text(label).Bold().FontSize(9).AlignCenter();
                        table.Cell().Border(0.5f).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Padding(4).Text(value).FontSize(9);
                    }
                    else
                    {
                        table.Cell().Border(0.5f).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2)
                            .Background(QuestPDF.Helpers.Colors.Grey.Lighten4).Padding(4);
                        table.Cell().Border(0.5f).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2).Padding(4);
                    }
                }
            }
        });
    }
}

public class PageBreakSection : ILetterSection
{
    public string SectionTitle => string.Empty;

    public void Render(ColumnDescriptor column)
    {
        column.Item().PageBreak();
    }
}

public class SignatureData
{
    public string Name { get; set; } = string.Empty;
    public string? Position { get; set; }
    public string? Institution { get; set; }
}
