@WebAppMultiTenant_HostAddress = http://localhost:5251

GET {{WebAppMultiTenant_HostAddress}}/api/users
Accept: application/json
x-tenant: tenantA

###
GET {{WebAppMultiTenant_HostAddress}}/api/users
Accept: application/json
x-tenant: tenantB
